[[redirects]]
  from = "/"
  to = "/favicon-generator/image"
  status = 302
  force = true

[[redirects]]
  from = "/favicon-generator"
  to = "/favicon-generator/image"
  status = 301
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

  